name: Setup frontend
description: Sets up the SDash frontend.

inputs:
  node-version:
    description: The version of Node.js to be used.
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Frontend dependencies
      run: npm install
      shell: bash