name: Setup backend
description: Sets up the SDash backend (database, cache server, dependencies).

inputs:
  redis_version:
    description: The version of redis that is used.
    required: true
  php_version:
    description: The version of PHP the backend runs on.
    required: true
  db_name:
    description: The name of the database that is created.
    required: true
  db_user:
    description: The username of the database user that is created. Needed to later access the database.
    required: true
  db_password:
    description: The password of the database user that is created. Needed to later access the database.
    required: true
  db_root_user:
    description: The username of the database root user. Needed to set up the database.
    required: true
  db_root_password:
    description: The password of the database root user. Needed to set up the database.
    required: true

runs:
  using: "composite"

  steps:
    # MySQL is included in the virtual environment:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    - name: Start MySQL
      run: sudo systemctl start mysql.service
      shell: bash

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ inputs.redis_version }}

    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ inputs.php_version }}

    - name: Install Backend Dependencies
      # This action has caching built in
      uses: ramsey/composer-install@v1

    - name: Create Database and User
      run: mysql -e "CREATE DATABASE ${{ inputs.db_name }}; CREATE USER '${{ inputs.db_user }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ inputs.db_password }}'; GRANT ALL ON ${{ inputs.db_name }}.* TO '${{ inputs.db_user }}'@'localhost';" -u${{ inputs.db_root_user }} -p${{ inputs.db_root_password }}
      shell: bash

    - name: Migrate Database
      run: php artisan migrate
      shell: bash

    - name: Generate key and passport encryption keys
      run: php artisan key:generate
      shell: bash