name: Deployment
concurrency: deployment
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    # Setup steps
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
    - name: Install Backend Dependencies
      uses: ramsey/composer-install@v1
    - name: Deploy
      uses: deployphp/action@master
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }}
        dep: deploy -v