name: SDash Tests

on: [push, pull_request]

env:
  DB_NAME: laravel_db
  DB_USER: laravel_db_user
  DB_PASSWORD: laravel_db_password
  DB_ROOT_USER: root
  DB_ROOT_PASSWORD: root

jobs:
  laravel-tests:
    strategy:
        matrix:
          ubuntu-version: [18.04]
          redis-version: [6]
          php-version: [7.4]

    runs-on: ubuntu-${{ matrix.ubuntu-version }}

    steps:
    # MySQL is included in the virtual environment:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Start Redis
      uses: supercharge/redis-github-action@1.2.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ matrix.php-version }}

    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Copy .env
      run: php -r "copy('.env.ci', '.env');"

    - name: Install Dependencies
      run: |
        composer update --no-ansi --no-interaction
        composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key and passport encryption keys
      run: |
        php artisan key:generate
        php artisan passport:install

    - name: Create Database and User
      run: mysql -e "CREATE DATABASE ${{ env.DB_NAME }}; CREATE USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ env.DB_PASSWORD }}'; GRANT ALL ON ${{ env.DB_NAME }}.* TO '${{ env.DB_USER }}'@'localhost';" -u${{ env.DB_ROOT_USER }} -p${{ env.DB_ROOT_PASSWORD }}

    - name: Migrate Database
      run: php artisan migrate

    - name: Run tests
      run: php artisan test
