on: push

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
    # Setup steps
    - uses: actions/checkout@v2
    - run: cp .env.ci .env
    - uses: ./.github/actions/setup-backend
    - uses: ./.github/actions/build-frontend
      with:
        env_file: .env.ci

    # Backend tests
    - name: Run backend tests
      run: php artisan test

    # End-to-end tests
    - name: Start the server for the end-to-end tests
      run: php artisan serve --port 8080 &
    - name: Run end-to-end tests
      run: npx nightwatch --headless --env firefox,chrome

  release:
    needs: tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/release-frontend
      with:
        env_file: .env.dev
        tag: dev
        allow_override: true