name: Release

on:
  push:
    branches:
    - main

jobs:
  frontend-build-for-dev-deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy .env
      run: cp .env.dev.example .env.dev

    - name: Build frontend
      uses: './.github/actions/build-frontend'
      with:
        env_file: .env.dev

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev
        allow_override: true
        files: public/