name: Tests

on: push

env:
  DB_NAME: laravel_db
  DB_USER: laravel_db_user
  DB_PASSWORD: laravel_db_password
  DB_ROOT_USER: root
  DB_ROOT_PASSWORD: root
  redis-version: 6
  php-version: 7.4
  node-version: 14

jobs:
  build-frontend:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node_version }}
        cache: 'npm'

    - name: Install Frontend dependencies
      run: npm install

    - name: Build frontend
      run: ENV_FILE=.env.ci npm run production

    - name: Store frontend build output
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: public
        retention-days: 1

  test-backend:
    runs-on: ubuntu-18.04
    needs: build-frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy .env
      run: cp .env.ci .env
  
    - name: Set up backend
      uses: './.github/actions/setup-backend'
      with:
        redis_version: ${{ env.redis-version }}
        php_version: ${{ env.php-version }}
        db_name: ${{ env.DB_NAME }}
        db_user: ${{ env.DB_USER }}
        db_password: ${{ env.DB_PASSWORD }}
        db_root_user: ${{ env.DB_ROOT_USER }}
        db_root_password: ${{ env.DB_ROOT_PASSWORD }}

    - name: Fetch frontend build artifact
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Run backend tests
      run: php artisan test

  test-frontend:
    runs-on: ubuntu-18.04
    needs: build-frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy .env
      run: cp .env.ci .env
  
    - name: Set up backend
      uses: './.github/actions/setup-backend'
      with:
        redis_version: ${{ env.redis-version }}
        php_version: ${{ env.php-version }}
        db_name: ${{ env.DB_NAME }}
        db_user: ${{ env.DB_USER }}
        db_password: ${{ env.DB_PASSWORD }}
        db_root_user: ${{ env.DB_ROOT_USER }}
        db_root_password: ${{ env.DB_ROOT_PASSWORD }}

    - name: Fetch frontend build artifact
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Start the server for the frontend tests
      run: php artisan serve --port 8080 &

    - name: Run frontend tests
      run: npx nightwatch --headless --env firefox,chrome
